{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openuem.fullname" . }}-postgresql
  labels:
    {{- include "openuem.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "openuem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openuem.fullname" . }}-postgresql-headless
  labels:
    {{- include "openuem.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "openuem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
